export const TOUR_STEPS = [
  {
    id: "welcome",
    route: "/dashboard",
    selector: null,
    title: "Welcome to Mnemos",
    body: "A quick, 60-second look around — you can skip this at any point.",
  },
  {
    id: "nav-dashboard",
    route: "/dashboard",
    selector: '[data-tour="nav-dashboard"]',
    placement: "right",
    title: "Dashboard",
    body: "Your at-a-glance summary — recent memories, this month's spending, and quick actions.",
  },
  {
    id: "nav-expenses",
    route: "/dashboard",
    selector: '[data-tour="nav-expenses"]',
    placement: "right",
    title: "Expenses",
    body: "Log expenses directly, set budgets, and schedule recurring rules — no chat needed.",
  },
  {
    id: "nav-categories",
    route: "/dashboard",
    selector: '[data-tour="nav-categories"]',
    placement: "right",
    title: "Categories",
    body: "Organize spending into your own categories, each with a color and icon.",
  },
  {
    id: "nav-reports",
    route: "/dashboard",
    selector: '[data-tour="nav-reports"]',
    placement: "right",
    title: "Reports",
    body: "Deeper trends — spending over time, category breakdowns, and budget performance.",
  },
  {
    id: "nav-goals",
    route: "/dashboard",
    selector: '[data-tour="nav-goals"]',
    placement: "right",
    title: "Goals",
    body: "Set savings goals and track contributions toward them over time.",
  },
  {
    id: "nav-memories",
    route: "/dashboard",
    selector: '[data-tour="nav-memories"]',
    placement: "right",
    title: "Memories",
    body: "Anything you ask Mnemos to remember shows up here, and gets recalled in later conversations.",
  },
  {
    id: "chat-composer",
    route: "/chat",
    selector: '[data-tour="chat-composer"]',
    placement: "top",
    title: "Just talk to it",
    body: "Type naturally — “spent 200 on lunch”, “what's my budget?”, “remember I'm vegetarian” — Mnemos figures out the rest.",
  },
];
